### ISSUE TITLE
Unable to download monit tarball

### ISSUE THREAD

**Issue by mickengland** [William-Yeh/ansible-monit#1]
Hi,
I am testing out this role against a Vagrant instance and getting the following output:

TASK: [williamyeh.monit | copy scripts to server] ****************************\* 
ok: [default] => (item=check-monit.sh)

TASK: [williamyeh.monit | check if specific version of monit has been installed] **\* 
failed: [default] => {"changed": false, "cmd": "LC_ALL=\"en_US.UTF-8\" /tmp/check-monit.sh 5.17.1", "delta": "0:00:00.003040", "end": "2016-05-22 21:03:33.914928", "rc": 127, "start": "2016-05-22 21:03:33.911888", "stdout_lines": ["{ \"found\": false , \"not_found\": true  }"], "warnings": []}
stdout: { "found": false , "not_found": true  }
...ignoring

TASK: [williamyeh.monit | set internal variables for convenience] ************\* 
ok: [default]

TASK: [williamyeh.monit | set internal variables for convenience] ************\* 
skipping: [default]

TASK: [williamyeh.monit | download and uutar tarball] ************************\* 
failed: [default] => {"failed": true}
msg: Source 'https://github.com/William-Yeh/ansible-monit-tarball/releases/download/5.17.1/monit-5.17.1-linux-x64.tar.gz' does not exist

FATAL: all hosts have already failed -- aborting

I have verified that I can wget on the url presented in the output from both the host and the target vagrant instance so it doesn't appear to be a problem with the source path. This is one of the better roles I have seen for monit so I would love to get this resolved. Any ideas?

**Comment by mickengland** [comment]
I should add that I installed the role via galaxy and here is my playbook:

---

 # file: ws-monit.yml
 # Installs and configures monit system monitoring.
 # Modify monitrc.j2 to setup additional monitoring.
- hosts: all
   sudo: True
   roles:
  - williamyeh.monit
  
  vars:
    monit_conf_main: "templates/monitrc.j2"

**Comment by William-Yeh** [comment]
Hmmm, the following demo seems ok:
https://asciinema.org/a/46403
